---
version: "3"
services:
  flask:
    build: "."
    restart: always
    ports:
       - "8000:5000"
    depends_on:
      - db
    volumes:
      - ".:/app"

  db:
    image: "mysql:8.0.22"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: scrabble_db
      MYSQL_USER: scrabble
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./db:/var/lib/mysql